input:
    service:
          CSVService:         
              path: Subsample.csv        # some input csv
              delimiter: ","

    schema_map:
        #   categorical_cols:
        #       Claim Reference: clm_no 
        #       Line of Business Long Desc: clm_lob 
          text_cols:
              dl_gewerk: assigned_labels 
              de1_eks_postext: invoice_text 
        #   date_cols: 
        #       Date of Loss: clm_dol 
        #       Notification Date: clm_don 

        #   numeric_cols:
        #       Claim Amount EUR: clm_amt

output:
    service:
          PickleService:
              path: clm_out.pkl       
  
